name: Center Place Christian Theatre
shortName: CPCT
description: Center Place Christian Theatre (CPCT) is committed to producing quality, family friendly entertainment, while providing an uplifting environment and experience for its participants.
kaywords: Center Place Christian Theatre, CPCT, Live Performance, Play, Production, Broadway, Independence, Kansas City, CPRS
phone: (000) 000-0000
email: info@centerplacechristiantheatre.com
address1: 2921 TEPEE AVE
address2: INDEPENDENCE, MO 64057